### ISSUE TITLE
1.11.2 Server Crash

### ISSUE THREAD

**Issue by Endmateria** [ArtixAllMighty/SubLib#1]
https://gist.github.com/Endmateria/f41b0577ca3763614d3bdfaedfd185e0

Just updated to the new Sublib 1.11.2-1.2.0.0 from 1.11.2-1.1.4.1 and now server is crashing.  Works fine when I downgrade back to 1.1.4.1

MC 1.11.2
Forge 2310
Sublib 1.11.2-1.2.0.0

**Comment by IchigoGames** [comment]
ya im getting the same crash on server.

**Comment by IchigoGames** [comment]
i hope this is getting worked on its the only mod left i Cant update.
